### ISSUE TITLE
Input validation for kirby_score

### ISSUE THREAD

**Issue by marberts** [kinleyid/tempodisco#12]
`kibry_score()` doesn't validate `data`, which is particularly problematic because that argument isn't well documented. This can result is unhelpful errors.

``` r
library(tempodisco)

data("td_bc_single_ptpt")

td_bc_single_ptpt$imm_chosen <- as.character(td_bc_single_ptpt$imm_chosen)

kirby_score(td_bc_single_ptpt)
#> Error in !data$imm_chosen[(idx):(nrow(data) + 1)]: invalid argument type

td_bc_single_ptpt$imm_chosen <- NA

kirby_score(td_bc_single_ptpt)
#> Error in if (max_consistency < 0.75) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2024-11-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Part of openjournals/joss-reviews#7472.

**Comment by kinleyid** [comment]
I've created a data validation function (`validate_td_data()`) that's now used in many functions including `kirby_score()`
