### ISSUE TITLE
Exisiting tools for temporal discounting

### ISSUE THREAD

**Issue by marberts** [kinleyid/tempodisco#8]
How does this package relate to existing tools? For example, https://github.com/miyamot0/discountingtools. There should probably be some mention in the paper of how this package contributes to existing tools for modelling temporal discounting.

Part of openjournals/joss-reviews#7472.

**Comment by kinleyid** [comment]
I've added a paragraph to the paper on related software tools in 8cc54d164b3f6feefb6d820be53ad056f772c9dd!
